import i18next from "i18next";
import I18nextBrowserLanguageDetector from "i18next-browser-languagedetector";
import { initReactI18next } from "react-i18next";

i18next
  .use(initReactI18next)
  .use(I18nextBrowserLanguageDetector)
  .init({
    fallbackLng: "en",
    debug: false,
    resources: {
      tr: {
        translation: {
          login: "Login",
          register: "Register",
          logout: "Logout",
          room: "Room",
          eventCreate: "Create Event",
          invite: "Invite",
          invites: "Invites",
          balance: "Balance",
          days: "days",
          hours: "hours",
          minutes: "minutes",
          before: "before",
          roomName: "Room Name",
          roomCreate: "Create Room",
          roomDescription: "Room Description",
          roomTopPredictors: "Top Predictors",
          roomRichests: "Richests",
          username: "Username",
          password: "Password",
          amount: "Amount",
          event: "Event",
          events: "Events",
          eventName: "Event Name",
          eventDescription: "Event Description",
          optionName: "Option Name",
          optionOdds: "Option Odds",
          totalOdds: "Total Odds",
          date: "Date",
          status: "Status",
          inProgress: "In Progress",
          won: "Won",
          lost: "Lost",
          cancelled: "Cancelled",
          unknown: "Unknown",
          language: "Language",
          betSlips: "Bet Slips",
          public: "Public",
          yes: "Yes",
          no: "No",
          createRoom: "Create Room",
          searchRoom : "Search Room",
          profile: "Profile",
          eventCases: "Event Cases",
          addEventCase: "Add Event Case",
          guessOptions: "Guess Options",
          addGuessOption: "Add Guess Option",
          addGuessOptionCase: "Add Guess Option Case",
          guessOptionCases: "Guess Option Cases",
          caseName: "Case Name",
          currentGuessPaper: "Current Guess Paper",
          stakes: "Stakes",
          createGuessPaper: "Create Guess Paper",
          wins: "Wins",
          invitePeopleToRoom: "Invite Someone to Room",
          activeEvents: "Active Events",
          guessPapers: "Guess Papers",
          guessPaperDetails: "Guess Paper Details",
          private: "Private",
          owner: "Owner",
          memberCount: "Member Count",
          details: "Details",
          odds: "Odds",
          caseOptionName: "Case Option Name",
          finalize: "Finalize",
          readyEvents: "Ready Events",
          lendToken: "Lend Token",
          normal: "Normal",
          borderless: "Borderless"
        },
      },
      en: {
        translation: {
          login: "Login",
          register: "Register",
          logout: "Logout",
          room: "Room",
          eventCreate: "Create Event",
          invite: "Invite",
          invites: "Invites",
          balance: "Balance",
          days: "days",
          hours: "hours",
          minutes: "minutes",
          before: "before",
          roomName: "Room Name",
          roomCreate: "Create Room",
          roomDescription: "Room Description",
          roomTopPredictors: "Top Predictors",
          roomRichests: "Richests",
          username: "Username",
          password: "Password",
          amount: "Amount",
          event: "Event",
          events: "Events",
          eventName: "Event Name",
          eventDescription: "Event Description",
          optionName: "Option Name",
          optionOdds: "Option Odds",
          totalOdds: "Total Odds",
          date: "Date",
          status: "Status",
          inProgress: "In Progress",
          won: "Won",
          lost: "Lost",
          cancelled: "Cancelled",
          unknown: "Unknown",
          language: "Language",
          betSlips: "Bet Slips",
          public: "Public",
          yes: "Yes",
          no: "No",
          createRoom: "Create Room",
          searchRoom : "Search Room",
          profile: "Profile",
          eventCases: "Event Cases",
          addEventCase: "Add Event Case",
          guessOptions: "Guess Options",
          addGuessOption: "Add Guess Option",
          addGuessOptionCase: "Add Guess Option Case",
          guessOptionCases: "Guess Option Cases",
          caseName: "Case Name",
          currentGuessPaper: "Current Guess Paper",
          stakes: "Stakes",
          createGuessPaper: "Create Guess Paper",
          wins: "Wins",
          invitePeopleToRoom: "Invite Someone to Room",
          activeEvents: "Active Events",
          guessPapers: "Guess Papers",
          guessPaperDetails: "Guess Paper Details",
          private: "Private",
          owner: "Owner",
          memberCount: "Member Count",
          details: "Details",
          odds: "Odds",
          caseOptionName: "Case Option Name",
          finalize: "Finalize",
          readyEvents: "Ready Events",
          lendToken: "Lend Token",
          normal: "Normal",
          borderless: "Borderless"
        },
      },
    },
  });
